- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: enable and disable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y;dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  # - name: add user
  #   ansible.builtin.user:
  #     name : roboshop

  # - name: create a directory
  #   ansible.builtin.file:
  #     path: /app
  #     state: directory

  # - name: download a app
  #   ansible.builtin.get_url:
  #     url : curl -o /tmp/catalogue.zip https://roboshop-builds.s3.amazonaws.com/catalogue.zip
  #     dest: /app

  # - name: unzip a file
  #   ansible.builtin.unarchive:
  #     src: /app
  #     dest: /tmp/catalogue.zip

  # - name: install npm
  #   ansible.builtin.command: npm install

  # - name: copy catalogue service module
  #   ansible.builtin.copy:
  #     src: catalogue.service
  #     dest: /etc/systemd/system/catalogue.service

  # - name: daemon reload
  #   ansible.builtin.systemd_service:
  #     name : daemon-reload
  #     state: reloaded

  # - name: start and enable service
  #   ansible.builtin.service:
  #     name: catalogue
  #     state: started
  #     enabled: yes

  # - name: copy mongo.repo 
  #   ansible.builtin.copy:
  #     src: mongodb.repo
  #     dest: /etc/yum.repos.d/mongodb.repo

  # - name: install mongodb client package
  #   ansible.builtin.package:
  #     name: mongodb-org-shell
  #     state: present
